### ISSUE TITLE
大佬报错啦 configparser.NoSectionError: No section: 'kuaidaili'

### ISSUE THREAD

**Issue by Cha0sJ** [1itt1eB0y/MyCollection#1]
Traceback (most recent call last):
  File "/ShuiZe_0x727/ShuiZe.py", line 1642, in <module>
    _init()
  File "/ShuiZe_0x727/ShuiZe.py", line 1468, in _init
    kuaidaili_tunnel = cf.get('kuaidaili', 'tunnel')
  File "/usr/local/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'kuaidaili'

**Comment by 1itt1eB0y** [comment]
如果使用快代理的话需要把`iniFile`文件夹下的对应文件挂载`volume`映射到容器内。
命令参考 `docker run -v yourIniFile:/ShuiZe_0x727/iniFile/config.ini`

**Comment by 1itt1eB0y** [comment]
可以把你运行的时候用的命令贴一下，我尝试复现一下

**Comment by Cha0sJ** [comment]
就是直接./Suize的时候就出现的，但是我没用代理 直接输入的

**Comment by 1itt1eB0y** [comment]
里面有个默认的`volume`挂载参数，会挂载当前目录下的`iniFile`文件夹到容器内，如果你本地没有这个文件夹，就会覆盖容器内原有文件夹为空文件夹，而不是将容器内的文件映射出来。
可以把文件内容改成如下：
```bash
docker run -it -v $(pwd)/result:/ShuiZe_0x727/result --name shuize 1itt1eb0y/shuize:latest $1
```
或者直接用这个命令跑

**Comment by 1itt1eB0y** [comment]
没有什么问题我先将issue关闭了
